### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by belauzas** [front-end-by-rimantas/7-grupe-portfolio#2]
- [x] logo
- [x] headeris prikibęs viršuje
- [x] navigacija
- [x] truputį pa'scroll'inus turi pasikeisti dizainas
- [x] nuorodos aktyvumas priklausomai nuo kur esu nu'scroll'ines turinyje
- [x] perkrovus puslapį, ir esant pa'scroll'inus, aktyvi nuoroda turi automatiškai būti tinkamai parinkta

**Comment by JonasChair** [comment]
Apsiimsiu siuo punktu.

**Comment by JonasChair** [comment]
#15
